/* AUTO-GENERATED by scripts/generate-data.mjs — do not hand-edit.
 *
 * 54 patients: 47 already owned by a coordinator, 7 in the
 * unassigned queue. 16 carry an authored Epic/Salesforce score split; the
 * rest show no breakdown rather than a fabricated one.
 */
import type { Coordinator, Patient, Settings } from '@/session/types'

export const COORDINATORS: readonly Coordinator[] = [
  { id: "sarah", name: "Sarah Lin, RN", short: "Sarah Lin", team: "Post-Discharge A" },
  { id: "marcus", name: "Marcus Webb, RN", short: "Marcus Webb", team: "Post-Discharge A" },
  { id: "denise", name: "Denise Kaur, LCSW", short: "Denise Kaur", team: "Social Work" },
  { id: "anthony", name: "Anthony Russo, RN", short: "Anthony Russo", team: "Post-Discharge B" },
  { id: "priya", name: "Priya Raman, RN", short: "Priya Raman", team: "Post-Discharge B" },
  { id: "gerald", name: "Gerald Okafor, LCSW", short: "Gerald Okafor", team: "Social Work", away: true },
]

export const MANAGER = {
  id: 'james',
  name: "James Porter",
  role: "Manager, Care Coordination",
} as const

export const DEFAULT_SETTINGS: Settings = {
  highThreshold: 75,
  mediumThreshold: 40,
  contactWindowHours: 48,
  defaultCapacity: 15,
  notifyOnUnassigned: true,
}

export const SEED_PATIENTS: readonly Patient[] = [
  { mrn: "4820193", name: "Darnell Washington", age: 67, sex: "M", dx: "CHF Exacerbation", score: 88, assignedTo: "sarah", contacted: false, hoursSince: 72, lastOutcome: null, epicPts: 51, sfdcPts: 37 },
  { mrn: "7730021", name: "Robert Osei", age: 72, sex: "M", dx: "Sepsis Recovery", score: 84, assignedTo: "sarah", contacted: false, hoursSince: 24, lastOutcome: null, epicPts: 55, sfdcPts: 29 },
  { mrn: "2214870", name: "Gloria Mensah", age: 79, sex: "F", dx: "COPD Exacerbation", score: 81, assignedTo: "sarah", contacted: true, hoursSince: 48, lastOutcome: "Left voicemail", epicPts: 49, sfdcPts: 32 },
  { mrn: "9081234", name: "Curtis Bell", age: 58, sex: "M", dx: "Diabetic Ketoacidosis", score: 77, assignedTo: "sarah", contacted: true, hoursSince: 96, lastOutcome: "Reached", epicPts: 47, sfdcPts: 30 },
  { mrn: "3310485", name: "Maria Okonkwo", age: 54, sex: "F", dx: "COPD", score: 62, assignedTo: "sarah", contacted: true, hoursSince: 168, lastOutcome: "Reached", epicPts: 36, sfdcPts: 26 },
  { mrn: "6612098", name: "Thomas Nguyen", age: 61, sex: "M", dx: "Post-Op Cardiac", score: 58, assignedTo: "sarah", contacted: true, hoursSince: 120, lastOutcome: "Reached", epicPts: 33, sfdcPts: 25 },
  { mrn: "4471102", name: "Yolanda Pierce", age: 48, sex: "F", dx: "Cellulitis", score: 51, assignedTo: "sarah", contacted: true, hoursSince: 144, lastOutcome: "Reached", epicPts: 28, sfdcPts: 23 },
  { mrn: "5540882", name: "Angela Torres", age: 44, sex: "F", dx: "Appendectomy", score: 22, assignedTo: "sarah", contacted: true, hoursSince: 120, lastOutcome: "Reached", epicPts: 12, sfdcPts: 10 },
  { mrn: "1129334", name: "Michael Adeyemi", age: 39, sex: "M", dx: "Laceration Repair", score: 17, assignedTo: "sarah", contacted: true, hoursSince: 192, lastOutcome: "Reached", epicPts: 9, sfdcPts: 8 },
  { mrn: "8820114", name: "Wanda Blackwell", age: 74, sex: "F", dx: "CHF Exacerbation", score: 86, assignedTo: "marcus", contacted: true, hoursSince: 48, lastOutcome: "Left voicemail" },
  { mrn: "5510298", name: "Hector Ramirez", age: 69, sex: "M", dx: "Pneumonia", score: 80, assignedTo: "marcus", contacted: true, hoursSince: 72, lastOutcome: "Reached" },
  { mrn: "7719023", name: "Deborah Chen", age: 66, sex: "F", dx: "Acute Kidney Injury", score: 78, assignedTo: "marcus", contacted: false, hoursSince: 24, lastOutcome: null },
  { mrn: "3348871", name: "Leonard Pike", age: 71, sex: "M", dx: "GI Bleed", score: 74, assignedTo: "marcus", contacted: true, hoursSince: 96, lastOutcome: "Reached" },
  { mrn: "9902143", name: "Sandra Whitfield", age: 57, sex: "F", dx: "COPD", score: 64, assignedTo: "marcus", contacted: true, hoursSince: 144, lastOutcome: "Reached" },
  { mrn: "2264490", name: "Omar Haddad", age: 52, sex: "M", dx: "Afib", score: 55, assignedTo: "marcus", contacted: true, hoursSince: 120, lastOutcome: "Reached" },
  { mrn: "6673321", name: "Janet Kowalski", age: 60, sex: "F", dx: "Post-Op Orthopedic", score: 43, assignedTo: "marcus", contacted: true, hoursSince: 168, lastOutcome: "Reached" },
  { mrn: "4419087", name: "Terrence Boyd", age: 41, sex: "M", dx: "Asthma", score: 28, assignedTo: "marcus", contacted: true, hoursSince: 216, lastOutcome: "Reached" },
  { mrn: "7761200", name: "Ruth Ellery", age: 83, sex: "F", dx: "Stroke / TIA", score: 91, assignedTo: "denise", contacted: true, hoursSince: 48, lastOutcome: "Reached" },
  { mrn: "5583012", name: "Clarence Muhammad", age: 78, sex: "M", dx: "CHF Exacerbation", score: 87, assignedTo: "denise", contacted: true, hoursSince: 72, lastOutcome: "Reached" },
  { mrn: "3392218", name: "Pearl Dominguez", age: 80, sex: "F", dx: "Sepsis Recovery", score: 85, assignedTo: "denise", contacted: true, hoursSince: 24, lastOutcome: "Reached" },
  { mrn: "8817745", name: "Vernon Ashby", age: 75, sex: "M", dx: "COPD Exacerbation", score: 83, assignedTo: "denise", contacted: true, hoursSince: 96, lastOutcome: "Reached" },
  { mrn: "2209983", name: "Ida Nkemelu", age: 72, sex: "F", dx: "Acute Kidney Injury", score: 79, assignedTo: "denise", contacted: true, hoursSince: 120, lastOutcome: "Left voicemail" },
  { mrn: "6640021", name: "Stanley Grubbs", age: 68, sex: "M", dx: "Diabetic Ketoacidosis", score: 76, assignedTo: "denise", contacted: true, hoursSince: 48, lastOutcome: "Reached" },
  { mrn: "4472290", name: "Loretta Sims", age: 81, sex: "F", dx: "Pneumonia", score: 75, assignedTo: "denise", contacted: true, hoursSince: 144, lastOutcome: "Reached" },
  { mrn: "9938104", name: "Eugene Tran", age: 64, sex: "M", dx: "GI Bleed", score: 59, assignedTo: "denise", contacted: true, hoursSince: 192, lastOutcome: "Reached" },
  { mrn: "5529940", name: "Frances Okoro", age: 76, sex: "F", dx: "CHF Exacerbation", score: 89, assignedTo: "anthony", contacted: false, hoursSince: 72, lastOutcome: null },
  { mrn: "7714488", name: "Dale Hutchins", age: 70, sex: "M", dx: "Sepsis Recovery", score: 82, assignedTo: "anthony", contacted: false, hoursSince: 48, lastOutcome: null },
  { mrn: "3361027", name: "Bernice Colvin", age: 73, sex: "F", dx: "COPD Exacerbation", score: 80, assignedTo: "anthony", contacted: false, hoursSince: 96, lastOutcome: null },
  { mrn: "8843319", name: "Ricardo Peña", age: 65, sex: "M", dx: "Pneumonia", score: 78, assignedTo: "anthony", contacted: false, hoursSince: 24, lastOutcome: null },
  { mrn: "2287701", name: "Marlene Shaw", age: 69, sex: "F", dx: "Acute Kidney Injury", score: 76, assignedTo: "anthony", contacted: true, hoursSince: 120, lastOutcome: "Left voicemail" },
  { mrn: "6619940", name: "Alvin Brooks", age: 62, sex: "M", dx: "Post-Op Cardiac", score: 75, assignedTo: "anthony", contacted: false, hoursSince: 72, lastOutcome: null },
  { mrn: "4490128", name: "Constance Yu", age: 56, sex: "F", dx: "Afib", score: 61, assignedTo: "anthony", contacted: true, hoursSince: 168, lastOutcome: "Reached" },
  { mrn: "9971203", name: "Darryl Means", age: 50, sex: "M", dx: "Cellulitis", score: 47, assignedTo: "anthony", contacted: true, hoursSince: 144, lastOutcome: "Reached" },
  { mrn: "5504417", name: "Hollis Barnett", age: 45, sex: "M", dx: "Appendectomy", score: 24, assignedTo: "anthony", contacted: true, hoursSince: 216, lastOutcome: "Reached" },
  { mrn: "7742891", name: "Estelle Rivers", age: 77, sex: "F", dx: "CHF Exacerbation", score: 84, assignedTo: "priya", contacted: true, hoursSince: 48, lastOutcome: "Reached" },
  { mrn: "3319974", name: "Nathaniel Park", age: 71, sex: "M", dx: "COPD", score: 73, assignedTo: "priya", contacted: true, hoursSince: 96, lastOutcome: "Reached" },
  { mrn: "8871140", name: "Juanita Delgado", age: 67, sex: "F", dx: "Pneumonia", score: 68, assignedTo: "priya", contacted: true, hoursSince: 72, lastOutcome: "Reached" },
  { mrn: "2230018", name: "Wesley Frazier", age: 59, sex: "M", dx: "Diabetic Ketoacidosis", score: 57, assignedTo: "priya", contacted: true, hoursSince: 144, lastOutcome: "Reached" },
  { mrn: "6690273", name: "Charlotte Ibe", age: 53, sex: "F", dx: "Post-Op Orthopedic", score: 45, assignedTo: "priya", contacted: true, hoursSince: 120, lastOutcome: "Reached" },
  { mrn: "4438852", name: "Simon Kowalczyk", age: 47, sex: "M", dx: "Asthma", score: 31, assignedTo: "priya", contacted: true, hoursSince: 192, lastOutcome: "Reached" },
  { mrn: "9917740", name: "Renee Caldwell", age: 42, sex: "F", dx: "Laceration Repair", score: 19, assignedTo: "priya", contacted: true, hoursSince: 240, lastOutcome: "Reached" },
  { mrn: "5567103", name: "Mildred Anyanwu", age: 85, sex: "F", dx: "Stroke / TIA", score: 90, assignedTo: "gerald", contacted: true, hoursSince: 72, lastOutcome: "Reached" },
  { mrn: "7798821", name: "Percy Lattimore", age: 79, sex: "M", dx: "CHF Exacerbation", score: 81, assignedTo: "gerald", contacted: true, hoursSince: 120, lastOutcome: "Left voicemail" },
  { mrn: "3374460", name: "Geneva Suarez", age: 74, sex: "F", dx: "Sepsis Recovery", score: 77, assignedTo: "gerald", contacted: true, hoursSince: 96, lastOutcome: "Reached" },
  { mrn: "8829015", name: "Otis Mbeki", age: 70, sex: "M", dx: "COPD Exacerbation", score: 72, assignedTo: "gerald", contacted: true, hoursSince: 144, lastOutcome: "Reached" },
  { mrn: "2251199", name: "Roberta Finch", age: 63, sex: "F", dx: "Acute Kidney Injury", score: 54, assignedTo: "gerald", contacted: true, hoursSince: 168, lastOutcome: "Reached" },
  { mrn: "6604428", name: "Andre Whitlock", age: 55, sex: "M", dx: "Afib", score: 38, assignedTo: "gerald", contacted: true, hoursSince: 216, lastOutcome: "Reached" },
  { mrn: "8813402", name: "Patricia Vaughn", age: 71, sex: "F", dx: "CHF Exacerbation", score: 88, assignedTo: null, contacted: false, hoursSince: 51, lastOutcome: null, epicPts: 52, sfdcPts: 36 },
  { mrn: "5529118", name: "Andre Coleman", age: 64, sex: "M", dx: "Sepsis Recovery", score: 85, assignedTo: null, contacted: false, hoursSince: 44, lastOutcome: null, epicPts: 55, sfdcPts: 30 },
  { mrn: "3390771", name: "Rosa Jiménez", age: 68, sex: "F", dx: "COPD", score: 82, assignedTo: null, contacted: false, hoursSince: 38, lastOutcome: null, epicPts: 48, sfdcPts: 34 },
  { mrn: "7742019", name: "Keith Braxton", age: 59, sex: "M", dx: "Diabetic Ketoacidosis", score: 79, assignedTo: null, contacted: false, hoursSince: 31, lastOutcome: null, epicPts: 44, sfdcPts: 35 },
  { mrn: "2201947", name: "Eleanor Whitaker", age: 77, sex: "F", dx: "Pneumonia", score: 76, assignedTo: null, contacted: false, hoursSince: 27, lastOutcome: null, epicPts: 46, sfdcPts: 30 },
  { mrn: "6638210", name: "Miguel Santos", age: 63, sex: "M", dx: "CHF Exacerbation", score: 75, assignedTo: null, contacted: false, hoursSince: 22, lastOutcome: null, epicPts: 47, sfdcPts: 28 },
  { mrn: "9917305", name: "Brenda Dunlap", age: 70, sex: "F", dx: "Post-Op Cardiac", score: 73, assignedTo: null, contacted: false, hoursSince: 19, lastOutcome: null, epicPts: 43, sfdcPts: 30 },
]
