/* AUTO-GENERATED by scripts/generate-data.mjs — do not hand-edit.
 *
 * The authored narrative for 9 patients: scored risk factors,
 * Epic-vs-Salesforce conflicts, next best actions and timeline moments.
 * Factor points sum to epicPts / sfdcPts, which sum to score — enforced by
 * src/data/invariants.ts.
 */
import type { PatientDetail } from './types'

export const PATIENT_DETAIL: readonly PatientDetail[] = [
  {
    "mrn": "4820193",
    "dischargedOn": "Sep 14",
    "dischargedAgo": "3 days ago",
    "assignedOn": "Sep 15",
    "nextAction": "📞 Call today",
    "authoredTier": "high",
    "admit": {
      "desc": "Admitted via Emergency — CHF exacerbation, shortness of breath.",
      "time": "Sep 11, 2026 · 11:42 PM"
    },
    "discharge": {
      "desc": "Discharge orders signed. Furosemide 40mg prescribed.",
      "time": "Sep 14, 2026 · 9:15 AM"
    },
    "factors": [
      {
        "text": "2 prior ED readmissions in last 90 days",
        "src": "epic",
        "pts": 24
      },
      {
        "text": "CHF primary diagnosis with prior exacerbation",
        "src": "epic",
        "pts": 18
      },
      {
        "text": "Furosemide refill not picked up — 4 days overdue",
        "src": "epic",
        "pts": 9
      },
      {
        "text": "No PCP follow-up appointment scheduled",
        "src": "sfdc",
        "pts": 16
      },
      {
        "text": "Zero engagement touchpoints since discharge",
        "src": "sfdc",
        "pts": 14
      },
      {
        "text": "Lives alone — no caregiver contact on file",
        "src": "sfdc",
        "pts": 12
      },
      {
        "text": "Enrolled in MyChart and opted in to SMS",
        "src": "sfdc",
        "pts": -5
      }
    ],
    "conflicts": [
      {
        "head": "Conflicting phone numbers",
        "a": {
          "src": "epic",
          "value": "(773) 555-0142"
        },
        "b": {
          "src": "sfdc",
          "value": "(312) 555-0198"
        },
        "verdict": "Using Salesforce number.",
        "why": "Patient answered on this line 6 days ago during a Marketing Cloud SMS reply. Epic number last verified 14 months ago."
      },
      {
        "head": "Discharge status mismatch",
        "a": {
          "src": "epic",
          "value": "Discharged Sep 14"
        },
        "b": {
          "src": "sfdc",
          "value": "Case: Inpatient"
        },
        "verdict": "Trusting Epic.",
        "why": "Epic is source of truth for clinical status. Salesforce case did not close — sync lag. Flagged for admin cleanup."
      }
    ],
    "actions": [
      {
        "icon": "📞",
        "tone": "call",
        "ai": true,
        "label": "Recommended · High Priority",
        "title": "Outbound Post-Discharge Call",
        "desc": "Patient has not been contacted since discharge 3 days ago. Medication pickup unconfirmed. Best call window: today before 5pm.",
        "prov": "reason",
        "buttons": [
          {
            "text": "Log Call",
            "kind": "primary"
          },
          {
            "text": "Dismiss",
            "kind": "ghost"
          }
        ]
      },
      {
        "icon": "🏥",
        "tone": "visit",
        "ai": true,
        "label": "Recommended · Medium Priority",
        "title": "Schedule PCP Follow-Up",
        "desc": "No follow-up within 7 days of discharge. CHF patients without follow-up readmit at 2.4× the rate.",
        "prov": "mychart",
        "buttons": [
          {
            "text": "Open MyChart",
            "kind": "secondary"
          },
          {
            "text": "Dismiss",
            "kind": "ghost"
          }
        ]
      },
      {
        "icon": "💊",
        "tone": "rx",
        "ai": false,
        "label": "Automated · One-Click Trigger",
        "title": "Send Medication Reminder SMS",
        "desc": "Furosemide 40mg refill is 4 days overdue. Patient is SMS opted-in.",
        "prov": "rxSms",
        "buttons": [
          {
            "text": "Send Now",
            "kind": "secondary"
          },
          {
            "text": "Dismiss",
            "kind": "ghost"
          }
        ]
      }
    ]
  },
  {
    "mrn": "7730021",
    "dischargedOn": "Sep 16",
    "dischargedAgo": "1 day ago",
    "assignedOn": "Sep 16",
    "nextAction": "📞 Call today",
    "authoredTier": "high",
    "admit": {
      "desc": "Admitted via Emergency — severe sepsis, urinary source. ICU 3 days.",
      "time": "Sep 12, 2026 · 4:18 AM"
    },
    "discharge": {
      "desc": "IV antibiotics completed. Oral step-down course prescribed, 7 days.",
      "time": "Sep 16, 2026 · 11:20 AM"
    },
    "factors": [
      {
        "text": "Severe sepsis with 3-day ICU stay this admission",
        "src": "epic",
        "pts": 22
      },
      {
        "text": "Age 72 with stage 3 chronic kidney disease",
        "src": "epic",
        "pts": 20
      },
      {
        "text": "Oral antibiotic step-down not yet verified",
        "src": "epic",
        "pts": 13
      },
      {
        "text": "No post-discharge contact attempted",
        "src": "sfdc",
        "pts": 15
      },
      {
        "text": "No caregiver or emergency contact on file",
        "src": "sfdc",
        "pts": 11
      },
      {
        "text": "2 missed appointments in prior 12 months",
        "src": "sfdc",
        "pts": 8
      },
      {
        "text": "Mobile number verified, SMS opted in",
        "src": "sfdc",
        "pts": -5
      }
    ],
    "conflicts": [
      {
        "head": "Active medication list mismatch",
        "a": {
          "src": "epic",
          "value": "7 active medications"
        },
        "b": {
          "src": "sfdc",
          "value": "4 active medications"
        },
        "verdict": "Trusting Epic.",
        "why": "Three antibiotics were added at discharge yesterday and have not yet propagated to the Salesforce care plan. Reconcile on first call."
      }
    ],
    "actions": [
      {
        "icon": "📞",
        "tone": "call",
        "ai": true,
        "label": "Recommended · High Priority",
        "title": "Outbound Post-Discharge Call",
        "desc": "Discharged 1 day ago after ICU-level sepsis care. Highest-yield window for catching early deterioration is the first 48 hours.",
        "prov": "reason",
        "buttons": [
          {
            "text": "Log Call",
            "kind": "primary"
          },
          {
            "text": "Dismiss",
            "kind": "ghost"
          }
        ]
      },
      {
        "icon": "💊",
        "tone": "rx",
        "ai": true,
        "label": "Recommended · High Priority",
        "title": "Verify Oral Antibiotic Step-Down",
        "desc": "Step-down course must start within 24 hours of the last IV dose. Pharmacy pickup is unconfirmed.",
        "prov": "reason",
        "buttons": [
          {
            "text": "Check Pharmacy",
            "kind": "secondary"
          },
          {
            "text": "Dismiss",
            "kind": "ghost"
          }
        ]
      },
      {
        "icon": "⚠️",
        "tone": "alert",
        "ai": false,
        "label": "Data Gap · Blocks Escalation",
        "title": "Capture Emergency Contact",
        "desc": "No caregiver on file. Required before after-hours escalation can be routed.",
        "prov": "healthCloud",
        "buttons": [
          {
            "text": "Add Contact",
            "kind": "secondary"
          },
          {
            "text": "Dismiss",
            "kind": "ghost"
          }
        ]
      }
    ]
  },
  {
    "mrn": "2214870",
    "dischargedOn": "Sep 15",
    "dischargedAgo": "2 days ago",
    "assignedOn": "Sep 15",
    "nextAction": "📞 Retry call",
    "authoredTier": "high",
    "admit": {
      "desc": "Admitted via Emergency — COPD exacerbation, hypoxia on room air.",
      "time": "Sep 12, 2026 · 7:33 PM"
    },
    "discharge": {
      "desc": "Prednisone taper and rescue inhaler prescribed. Home oxygen continued.",
      "time": "Sep 15, 2026 · 10:05 AM"
    },
    "factors": [
      {
        "text": "3rd COPD exacerbation in the last 12 months",
        "src": "epic",
        "pts": 21
      },
      {
        "text": "Age 79, dependent on continuous home oxygen",
        "src": "epic",
        "pts": 17
      },
      {
        "text": "Inhaler technique not documented at discharge",
        "src": "epic",
        "pts": 11
      },
      {
        "text": "Voicemail only — no live contact since discharge",
        "src": "sfdc",
        "pts": 14
      },
      {
        "text": "No pulmonary rehab referral scheduled",
        "src": "sfdc",
        "pts": 12
      },
      {
        "text": "Transportation barrier flagged in prior case",
        "src": "sfdc",
        "pts": 9
      },
      {
        "text": "Daughter listed as active caregiver contact",
        "src": "sfdc",
        "pts": -3
      }
    ],
    "conflicts": [
      {
        "head": "Caregiver contact disagreement",
        "a": {
          "src": "epic",
          "value": "No caregiver listed"
        },
        "b": {
          "src": "sfdc",
          "value": "Daughter — (773) 555-0281"
        },
        "verdict": "Using Salesforce contact.",
        "why": "Daughter was added during a care management call in July and has since answered twice. Epic demographic record predates that."
      }
    ],
    "actions": [
      {
        "icon": "📞",
        "tone": "call",
        "ai": true,
        "label": "Recommended · High Priority",
        "title": "Retry Call — Try Caregiver Line",
        "desc": "Voicemail left yesterday with no callback. Daughter has answered on the secondary line twice before.",
        "prov": "reason",
        "buttons": [
          {
            "text": "Log Call",
            "kind": "primary"
          },
          {
            "text": "Dismiss",
            "kind": "ghost"
          }
        ]
      },
      {
        "icon": "🏥",
        "tone": "visit",
        "ai": true,
        "label": "Recommended · High Priority",
        "title": "Schedule Pulmonary Rehab Intake",
        "desc": "Third exacerbation this year with no rehab referral on file. Rehab within 30 days cuts repeat exacerbation risk substantially.",
        "prov": "mychart",
        "buttons": [
          {
            "text": "Open MyChart",
            "kind": "secondary"
          },
          {
            "text": "Dismiss",
            "kind": "ghost"
          }
        ]
      },
      {
        "icon": "⚠️",
        "tone": "alert",
        "ai": true,
        "label": "Recommended · Medium Priority",
        "title": "Arrange Transport for Follow-Up",
        "desc": "Transportation barrier documented in a prior case. Follow-up attendance is the main risk to this plan.",
        "prov": "healthCloud",
        "buttons": [
          {
            "text": "Request Transport",
            "kind": "secondary"
          },
          {
            "text": "Dismiss",
            "kind": "ghost"
          }
        ]
      }
    ],
    "events": [
      {
        "icon": "📞",
        "dot": "",
        "title": "Outbound Call — Voicemail Left",
        "desc": "No answer on verified mobile. Voicemail left with direct callback number.",
        "time": "Sep 16, 2026 · 2:10 PM",
        "src": "sfdc"
      }
    ]
  },
  {
    "mrn": "9081234",
    "dischargedOn": "Sep 13",
    "dischargedAgo": "4 days ago",
    "assignedOn": "Sep 13",
    "nextAction": "💊 Confirm Rx pickup",
    "authoredTier": "high",
    "admit": {
      "desc": "Admitted via Emergency — diabetic ketoacidosis, blood glucose 512.",
      "time": "Sep 10, 2026 · 2:55 AM"
    },
    "discharge": {
      "desc": "Insulin regimen revised to basal-bolus. Glucometer supplies issued.",
      "time": "Sep 13, 2026 · 2:40 PM"
    },
    "factors": [
      {
        "text": "2nd DKA admission in the last 6 months",
        "src": "epic",
        "pts": 20
      },
      {
        "text": "HbA1c 11.2% on admission",
        "src": "epic",
        "pts": 16
      },
      {
        "text": "Insulin regimen changed at discharge",
        "src": "epic",
        "pts": 11
      },
      {
        "text": "Reported insulin cost concern on last call",
        "src": "sfdc",
        "pts": 12
      },
      {
        "text": "Insulin prescription not picked up — 3 days",
        "src": "sfdc",
        "pts": 13
      },
      {
        "text": "No endocrinology follow-up booked",
        "src": "sfdc",
        "pts": 10
      },
      {
        "text": "Reached by phone 2 days ago — engaged",
        "src": "sfdc",
        "pts": -5
      }
    ],
    "conflicts": [
      {
        "head": "Preferred pharmacy disagreement",
        "a": {
          "src": "epic",
          "value": "Walgreens — 55th St"
        },
        "b": {
          "src": "sfdc",
          "value": "Mariano's — Hyde Park"
        },
        "verdict": "Using Salesforce pharmacy.",
        "why": "Patient stated the new pharmacy during the call 2 days ago. The Epic prescription was routed to the old location — likely why pickup has not happened."
      }
    ],
    "actions": [
      {
        "icon": "💊",
        "tone": "rx",
        "ai": true,
        "label": "Recommended · High Priority",
        "title": "Reroute and Confirm Insulin Pickup",
        "desc": "Prescription sits at the wrong pharmacy and is 3 days unclaimed. Missed insulin is the direct path back to DKA.",
        "prov": "reason",
        "buttons": [
          {
            "text": "Reroute Rx",
            "kind": "primary"
          },
          {
            "text": "Dismiss",
            "kind": "ghost"
          }
        ]
      },
      {
        "icon": "⚠️",
        "tone": "alert",
        "ai": true,
        "label": "Recommended · High Priority",
        "title": "Refer to Financial Assistance",
        "desc": "Patient raised insulin affordability on the last call. Cost is the stated barrier, so a reminder alone will not resolve it.",
        "prov": "healthCloud",
        "buttons": [
          {
            "text": "Start Referral",
            "kind": "secondary"
          },
          {
            "text": "Dismiss",
            "kind": "ghost"
          }
        ]
      },
      {
        "icon": "🏥",
        "tone": "visit",
        "ai": true,
        "label": "Recommended · Medium Priority",
        "title": "Book Endocrinology Follow-Up",
        "desc": "Regimen changed at discharge with no specialist follow-up scheduled.",
        "prov": "mychart",
        "buttons": [
          {
            "text": "Open MyChart",
            "kind": "secondary"
          },
          {
            "text": "Dismiss",
            "kind": "ghost"
          }
        ]
      }
    ],
    "events": [
      {
        "icon": "📞",
        "dot": "green",
        "title": "Outbound Call — Patient Reached",
        "desc": "Confirmed glucometer use. Raised concern about insulin cost. Pharmacy preference updated.",
        "time": "Sep 15, 2026 · 10:25 AM",
        "src": "sfdc"
      }
    ]
  },
  {
    "mrn": "3310485",
    "dischargedOn": "Sep 10",
    "dischargedAgo": "7 days ago",
    "assignedOn": "Sep 10",
    "nextAction": "📅 Schedule follow-up",
    "authoredTier": "medium",
    "admit": {
      "desc": "Admitted for COPD exacerbation — increased wheeze, productive cough.",
      "time": "Sep 8, 2026 · 1:12 PM"
    },
    "discharge": {
      "desc": "Bronchodilator regimen adjusted. Smoking cessation counselling offered.",
      "time": "Sep 10, 2026 · 9:50 AM"
    },
    "factors": [
      {
        "text": "COPD with 1 prior exacerbation this year",
        "src": "epic",
        "pts": 18
      },
      {
        "text": "Active smoker, documented at discharge",
        "src": "epic",
        "pts": 12
      },
      {
        "text": "Spirometry overdue by 8 months",
        "src": "epic",
        "pts": 6
      },
      {
        "text": "No PCP follow-up inside the 7-day window",
        "src": "sfdc",
        "pts": 14
      },
      {
        "text": "Declined pulmonary rehab referral",
        "src": "sfdc",
        "pts": 10
      },
      {
        "text": "Single engagement touchpoint since discharge",
        "src": "sfdc",
        "pts": 7
      },
      {
        "text": "Reached and responsive 4 days ago",
        "src": "sfdc",
        "pts": -5
      }
    ],
    "conflicts": [
      {
        "head": "SMS consent disagreement",
        "a": {
          "src": "epic",
          "value": "No messaging consent"
        },
        "b": {
          "src": "sfdc",
          "value": "SMS opted in — Aug 2026"
        },
        "verdict": "Using Salesforce consent.",
        "why": "Opt-in was captured through a Marketing Cloud campaign and is the more recent record. Outbound SMS is permitted."
      }
    ],
    "actions": [
      {
        "icon": "📅",
        "tone": "visit",
        "ai": true,
        "label": "Recommended · Medium Priority",
        "title": "Schedule PCP Follow-Up",
        "desc": "The 7-day post-discharge window closes today with no appointment booked.",
        "prov": "mychart",
        "buttons": [
          {
            "text": "Open MyChart",
            "kind": "secondary"
          },
          {
            "text": "Dismiss",
            "kind": "ghost"
          }
        ]
      },
      {
        "icon": "💬",
        "tone": "call",
        "ai": false,
        "label": "Automated · One-Click Trigger",
        "title": "Send Smoking Cessation Resources",
        "desc": "Active smoker who declined rehab. SMS consent is confirmed in Salesforce.",
        "prov": "sms",
        "buttons": [
          {
            "text": "Send Now",
            "kind": "secondary"
          },
          {
            "text": "Dismiss",
            "kind": "ghost"
          }
        ]
      }
    ],
    "events": [
      {
        "icon": "📞",
        "dot": "green",
        "title": "Outbound Call — Patient Reached",
        "desc": "Reported stable breathing. Declined pulmonary rehab referral.",
        "time": "Sep 13, 2026 · 3:40 PM",
        "src": "sfdc"
      }
    ]
  },
  {
    "mrn": "6612098",
    "dischargedOn": "Sep 12",
    "dischargedAgo": "5 days ago",
    "assignedOn": "Sep 12",
    "nextAction": "💬 Send SMS check-in",
    "authoredTier": "medium",
    "admit": {
      "desc": "Elective admission for coronary artery bypass graft, three vessels.",
      "time": "Sep 7, 2026 · 6:00 AM"
    },
    "discharge": {
      "desc": "Post-op day 5. Warfarin started — INR monitoring required weekly.",
      "time": "Sep 12, 2026 · 12:30 PM"
    },
    "factors": [
      {
        "text": "CABG — postoperative day 5 at discharge",
        "src": "epic",
        "pts": 15
      },
      {
        "text": "Anticoagulation requires weekly INR monitoring",
        "src": "epic",
        "pts": 12
      },
      {
        "text": "Mild post-operative anemia at discharge",
        "src": "epic",
        "pts": 6
      },
      {
        "text": "INR draw appointment not confirmed",
        "src": "sfdc",
        "pts": 12
      },
      {
        "text": "Cardiac rehab intake not scheduled",
        "src": "sfdc",
        "pts": 9
      },
      {
        "text": "Spouse travelling — limited home support this week",
        "src": "sfdc",
        "pts": 8
      },
      {
        "text": "Reached 3 days ago, reported feeling well",
        "src": "sfdc",
        "pts": -4
      }
    ],
    "conflicts": [],
    "actions": [
      {
        "icon": "⚠️",
        "tone": "alert",
        "ai": true,
        "label": "Recommended · High Priority",
        "title": "Confirm INR Draw Appointment",
        "desc": "Warfarin started at discharge with no confirmed lab visit. An unmonitored INR is the highest-consequence gap in this plan.",
        "prov": "reason",
        "buttons": [
          {
            "text": "Confirm Lab",
            "kind": "primary"
          },
          {
            "text": "Dismiss",
            "kind": "ghost"
          }
        ]
      },
      {
        "icon": "🏥",
        "tone": "visit",
        "ai": true,
        "label": "Recommended · Medium Priority",
        "title": "Schedule Cardiac Rehab Intake",
        "desc": "Post-CABG rehab enrolment is still open and improves 90-day outcomes.",
        "prov": "mychart",
        "buttons": [
          {
            "text": "Open MyChart",
            "kind": "secondary"
          },
          {
            "text": "Dismiss",
            "kind": "ghost"
          }
        ]
      },
      {
        "icon": "💬",
        "tone": "call",
        "ai": false,
        "label": "Automated · One-Click Trigger",
        "title": "Send SMS Check-In",
        "desc": "Spouse away this week. A light-touch check-in covers the gap in home support.",
        "prov": "sms",
        "buttons": [
          {
            "text": "Send Now",
            "kind": "secondary"
          },
          {
            "text": "Dismiss",
            "kind": "ghost"
          }
        ]
      }
    ],
    "events": [
      {
        "icon": "📞",
        "dot": "green",
        "title": "Outbound Call — Patient Reached",
        "desc": "Incision healing well, no chest pain. Spouse travel noted as a support gap.",
        "time": "Sep 14, 2026 · 11:05 AM",
        "src": "sfdc"
      }
    ]
  },
  {
    "mrn": "4471102",
    "dischargedOn": "Sep 11",
    "dischargedAgo": "6 days ago",
    "assignedOn": "Sep 11",
    "nextAction": "📅 Schedule follow-up",
    "authoredTier": "medium",
    "admit": {
      "desc": "Admitted for lower-leg cellulitis requiring intravenous antibiotics.",
      "time": "Sep 9, 2026 · 5:47 PM"
    },
    "discharge": {
      "desc": "Transitioned to oral antibiotics, 10-day course. Wound care instructions given.",
      "time": "Sep 11, 2026 · 1:15 PM"
    },
    "factors": [
      {
        "text": "Cellulitis with IV-to-oral antibiotic transition",
        "src": "epic",
        "pts": 13
      },
      {
        "text": "Type 2 diabetes — impaired wound healing",
        "src": "epic",
        "pts": 10
      },
      {
        "text": "Wound check not yet documented",
        "src": "epic",
        "pts": 5
      },
      {
        "text": "Wound care follow-up not scheduled",
        "src": "sfdc",
        "pts": 11
      },
      {
        "text": "Works two jobs — daytime contact difficult",
        "src": "sfdc",
        "pts": 9
      },
      {
        "text": "No email on file, SMS only",
        "src": "sfdc",
        "pts": 6
      },
      {
        "text": "Reached 5 days ago, antibiotics confirmed",
        "src": "sfdc",
        "pts": -3
      }
    ],
    "conflicts": [
      {
        "head": "Conflicting phone numbers",
        "a": {
          "src": "epic",
          "value": "(312) 555-0733"
        },
        "b": {
          "src": "sfdc",
          "value": "(872) 555-0119"
        },
        "verdict": "Using Salesforce number.",
        "why": "Epic number reaches a disconnected line. The Salesforce mobile answered 5 days ago and is the only working contact."
      }
    ],
    "actions": [
      {
        "icon": "🏥",
        "tone": "visit",
        "ai": true,
        "label": "Recommended · Medium Priority",
        "title": "Schedule Wound Care Follow-Up",
        "desc": "Diabetic patient mid-antibiotic course with no wound check booked. Healing needs to be verified before the course ends.",
        "prov": "mychart",
        "buttons": [
          {
            "text": "Open MyChart",
            "kind": "secondary"
          },
          {
            "text": "Dismiss",
            "kind": "ghost"
          }
        ]
      },
      {
        "icon": "💬",
        "tone": "call",
        "ai": true,
        "label": "Recommended · Low Priority",
        "title": "Send Evening SMS Check-In",
        "desc": "Works two jobs — daytime calls have not connected. Evening SMS matches the contact pattern that has worked.",
        "prov": "sms",
        "buttons": [
          {
            "text": "Schedule SMS",
            "kind": "secondary"
          },
          {
            "text": "Dismiss",
            "kind": "ghost"
          }
        ]
      }
    ],
    "events": [
      {
        "icon": "📞",
        "dot": "green",
        "title": "Outbound Call — Patient Reached",
        "desc": "Confirmed antibiotic adherence. Requested evening contact going forward.",
        "time": "Sep 12, 2026 · 6:20 PM",
        "src": "sfdc"
      }
    ]
  },
  {
    "mrn": "5540882",
    "dischargedOn": "Sep 12",
    "dischargedAgo": "5 days ago",
    "assignedOn": "Sep 12",
    "nextAction": "✓ Monitor only",
    "authoredTier": "low",
    "admit": {
      "desc": "Admitted via Emergency — acute appendicitis, no perforation.",
      "time": "Sep 11, 2026 · 8:05 AM"
    },
    "discharge": {
      "desc": "Laparoscopic appendectomy, uncomplicated. Routine analgesia prescribed.",
      "time": "Sep 12, 2026 · 10:40 AM"
    },
    "factors": [
      {
        "text": "Laparoscopic appendectomy — uncomplicated",
        "src": "epic",
        "pts": 8
      },
      {
        "text": "Post-op day 5, no complications documented",
        "src": "epic",
        "pts": 6
      },
      {
        "text": "No chronic conditions on file",
        "src": "epic",
        "pts": -2
      },
      {
        "text": "Post-op wound check not yet confirmed",
        "src": "sfdc",
        "pts": 7
      },
      {
        "text": "First admission — no engagement history",
        "src": "sfdc",
        "pts": 6
      },
      {
        "text": "Reached 4 days ago, recovering well",
        "src": "sfdc",
        "pts": -3
      }
    ],
    "conflicts": [],
    "actions": [
      {
        "icon": "💬",
        "tone": "call",
        "ai": false,
        "label": "Automated · One-Click Trigger",
        "title": "Send Post-Op Check-In SMS",
        "desc": "Routine day-7 recovery check. No clinical concerns outstanding.",
        "prov": "sms",
        "buttons": [
          {
            "text": "Send Now",
            "kind": "secondary"
          },
          {
            "text": "Dismiss",
            "kind": "ghost"
          }
        ]
      }
    ],
    "events": [
      {
        "icon": "📞",
        "dot": "green",
        "title": "Outbound Call — Patient Reached",
        "desc": "Recovering well, pain controlled. No further concerns raised.",
        "time": "Sep 13, 2026 · 9:30 AM",
        "src": "sfdc"
      }
    ]
  },
  {
    "mrn": "1129334",
    "dischargedOn": "Sep 9",
    "dischargedAgo": "8 days ago",
    "assignedOn": "Sep 9",
    "nextAction": "✓ Monitor only",
    "authoredTier": "low",
    "admit": {
      "desc": "Presented to Emergency — forearm laceration from a workplace injury.",
      "time": "Sep 9, 2026 · 3:22 PM"
    },
    "discharge": {
      "desc": "Nine sutures placed. Tetanus booster given. Removal due in 10 days.",
      "time": "Sep 9, 2026 · 6:50 PM"
    },
    "factors": [
      {
        "text": "Laceration repair, 9 sutures — removal due",
        "src": "epic",
        "pts": 7
      },
      {
        "text": "Tetanus booster administered",
        "src": "epic",
        "pts": 4
      },
      {
        "text": "No chronic conditions on file",
        "src": "epic",
        "pts": -2
      },
      {
        "text": "Suture removal appointment not booked",
        "src": "sfdc",
        "pts": 6
      },
      {
        "text": "No established primary care provider",
        "src": "sfdc",
        "pts": 5
      },
      {
        "text": "Reached 7 days ago, healing well",
        "src": "sfdc",
        "pts": -3
      }
    ],
    "conflicts": [],
    "actions": [
      {
        "icon": "📅",
        "tone": "visit",
        "ai": true,
        "label": "Recommended · Low Priority",
        "title": "Book Suture Removal",
        "desc": "Removal is due within 2 days and no appointment exists. Patient has no PCP to fall back on.",
        "prov": "mychart",
        "buttons": [
          {
            "text": "Open MyChart",
            "kind": "secondary"
          },
          {
            "text": "Dismiss",
            "kind": "ghost"
          }
        ]
      }
    ],
    "events": [
      {
        "icon": "📞",
        "dot": "green",
        "title": "Outbound Call — Patient Reached",
        "desc": "Wound clean and healing. Advised on suture removal timing.",
        "time": "Sep 10, 2026 · 4:15 PM",
        "src": "sfdc"
      }
    ]
  }
]

export const DETAIL_BY_MRN: ReadonlyMap<string, PatientDetail> = new Map(
  PATIENT_DETAIL.map((d) => [d.mrn, d]),
)
